# Generated by Django 3.1.3 on 2021-06-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='содержание',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='тема',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
